name: Semantic tags

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  packages: write

jobs:
  move-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          GITHUB: "${{ toJSON(github) }}"
        run: echo "${GITHUB}"
